name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: [17.x]

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

      - name: Unit Tests
        run: npm run test:unit

